import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

import { StateContext } from "./context/stateContext";
import { PrimeReactProvider } from "primereact/api";
import "primereact/resources/primereact.css";
import "primeflex/primeflex.css";
import "primeicons/primeicons.css";
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export async function generateMetadata() {
  return {
    title: "Create Next App",
    description: "Generated by create next app",
  };
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="top-right" />
        <PrimeReactProvider>
          <StateContext>{children}</StateContext>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
